{% set name = "cfgrib" %}
{% set version = "0.9.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fecbf819500d670596abcada2d7da275860fa8a774ccc9b39938caef23e95b03

build:
  noarch: python
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - pytest-runner
    - python
  run:
    - attrs
    - cffi
    - click
    - eccodes >=2.12.0
    - future
    - numpy
    - python
    - typing
    - xarray >=0.12.0

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - StephanSiemen
