{% set name = "cfgrib" %}
{% set version = "0.9.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb867c0b56dab1381b8ddbb2dd4da59406668d20596762b63d106bdb1b3e1208

build:
  noarch: python
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - attrs >=19.2.0
    - cffi
    - click
    - eccodes >=2.12.0
    - numpy
    - setuptools
    - xarray >=0.12.0

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - StephanSiemen
