{% set name = "cfgrib" %}
{% set version = "0.9.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34ef4a0334c1077f6ad7c15de1d8a79a0aa0980187b2848deb8cb8acb3755b74

build:
  noarch: python
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - attrs >=19.2
    - click
    - packaging
    - python-eccodes >=0.9.8
    - numpy
    - setuptools
    - xarray >=0.15

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - akrherz
    - StephanSiemen
    - iainrussell
