{% set name = "cfgrib" %}
{% set version = "0.9.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5990b7e7724ac76283cb8bff3e9b2d951dbb7964a418992b589e7cdca608d64

build:
  noarch: python
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - attrs >=19.2
    - click
    - python-eccodes >=2020.06
    - numpy
    - setuptools
    - xarray >=0.15

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - StephanSiemen
