travis:
  secure:
    BINSTAR_TOKEN: Qwhav9N2hzqNK/7r0U1B2+SG5AP/KGpVduN2+iyNEjgWcIWpIp9Ta/YHgarGrFkbJ4WlH2D7zBQlwcTt3aTlTuakw+2W3eOSsWywJhAwvz4PHOfpdl83kr9Ef6z3/TuJnRgh2O7U0pVFKWeLI7LWffKk/ljd3+KMMGuIlcAkHB426u4FIuyStD/7U2dTwRFlQodqZrK2yIH0zq3GJxPfO42Cw60h/e+fgy81yE7o4bo0PdCmCpa1jM5tRqWxNKYW98wM1zWw0MJTC+bd5JEbOx7+gs63KdLCYlxiQ+dPyTqb50BqcjwOAfkpUAS+mr1Vyqcxk2vmXT0YlwgC5i8nIFEVn+yXThy+fOiz/82u+0AKzWngVq9/vfsL14b9El6GOwFtS3xNJWt5q8qpP1EnOAnh/oHNetahme9K8A9szV3sojOyaKQ9mLStat9XNSu0UprRqoAXvFaNbbt19s/pIoDUWKXKDtLxEmf0X7IELBkBRLKIy/BcSEp7yuGKwGWRlAKylXQiWXMyS8UvR2WNXgpOrgTx2w0VXA8g+9nOGHF0Q2VGq63JiduqwPxCU0Zo1T0av5SA3bujgtuflY4xXwJtj45O31RMuUbYPr/kZYPOKmlmJKPMemMFBB3ioIYDFbNn/fuZWtfLx8ZKzj64b1ZY2GrAKC//5m7vRjbTiBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
